# Generated by Django 4.2.1 on 2023-09-25 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="file_Upload",
            fields=[
                ("ids", models.AutoField(primary_key=True, serialize=False)),
                ("file_name", models.CharField(max_length=255)),
                ("my_files", models.FileField(upload_to="")),
            ],
        ),
    ]
